### ISSUE TITLE
Most event text is barely if at all readable in the past

### ISSUE THREAD

**Issue by Lovasz-Akos** [dracula/google-calendar#1]
![image](https://github.com/dracula/google-calendar/assets/55391231/ed5599d6-08ab-40a7-a5be-46262802450b)

Past events are so faded they're basically unreadable, is this inteded?

**Comment by accountingnerd** [comment]
I was not aware of this issue. I've noticed that Google has made a few changes to their CSS. It's tough to keep up with all of them, unfortunately. I can take a look.

**Comment by Lovasz-Akos** [comment]
update: they made the header white lol
![image](https://github.com/dracula/google-calendar/assets/55391231/25b30ab9-66b0-4a27-9401-1b405cd0cde2)

**Comment by accountingnerd** [comment]
I saw that, too. They're killing me. :)

**Comment by accountingnerd** [comment]
I think I got the issue with the past events and the header fixed. 

@Lovasz-Akos -- can you give that a try and let me know if it's still causing problems?

**Comment by Lovasz-Akos** [comment]
yes it's much better!
