### ISSUE TITLE
Google Update made the screen light. 

### ISSUE THREAD

**Issue by accountingnerd** [dracula/google-calendar#3]
![image](https://github.com/dracula/google-calendar/assets/60153219/c7d84888-d426-4085-8374-e6b569a05181)

Need to review and look into this issue.

**Comment by sym-z** [comment]
I'm having the same issue. Looks like the theme is no longer having the same effect on the white portions of the calendar.

**Comment by accountingnerd** [comment]
I started looking at this yesterday, and they've made quite a few changes to the CSS. It's more than a quick fix, unfortunately. I'll work on this as I have time, and I welcome contributions if others have time as well.

**Comment by accountingnerd** [comment]
I got most of the issues sorted out, I think. Please let me know if you see new issues with the calendar.

**Comment by accountingnerd** [comment]
Still missing some of the key elements. I'm going to create a new issue to track the missing pieces.
