### ISSUE TITLE
Tasks are not styled at all

### ISSUE THREAD

**Issue by accountingnerd** [dracula/google-calendar#7]
When switching to the task view, the colors are not translated.

![image](https://github.com/dracula/google-calendar/assets/60153219/96ca9797-04d8-47c7-872c-2f1412393edd)

**Comment by Keith94** [comment]
+1 I mostly use Tasks so this would be great to have.

**Comment by accountingnerd** [comment]
@Keith94 -- give it a try now. I had some time tonight and I think I got most of it. If you see something odd, let me know.

**Comment by Keith94** [comment]
@accountingnerd Thanks for the quick update! I noticed a couple oddities.

The date/time background not styled, hard to read
![image](https://github.com/dracula/google-calendar/assets/5490615/644efa9a-d4d2-46bf-8341-1d6d2be0f384)
![brave_sFtgVsGsjo](https://github.com/dracula/google-calendar/assets/5490615/02c7dd3f-efe2-4cc4-b094-4c30b9ae59db)

The gradient at the end when hovering a task
![brave_pPqib34Qfc](https://github.com/dracula/google-calendar/assets/5490615/4e66caca-a7e8-443f-a1e5-d33571df8324)

EDIT: The details text is hard to read, too
![image](https://github.com/dracula/google-calendar/assets/5490615/2f0489cf-adea-443f-82f1-bedad7d85eb3)

EDIT2: The create dialogue is using vanilla colors
![image](https://github.com/dracula/google-calendar/assets/5490615/ffc612a1-0831-46d8-9107-14c1451eacfe)

Some white elements pop up when adding new task and dragging a task
![brave_ARIsFTB7ob](https://github.com/dracula/google-calendar/assets/5490615/f5497c3b-923f-44bd-9405-1e63c4e7d861)

Create button is white
![image](https://github.com/dracula/google-calendar/assets/5490615/0ee1a666-624a-42af-b353-d33b9c60ae26)

**Comment by accountingnerd** [comment]
Thanks, @Keith94. It may be a little while before I get to these, but I appreciate you pointing them out.

**Comment by accountingnerd** [comment]
Fixed the issues with the date/time, text hard to read, and the gradient.

Moving the other items to their own issue for tracking purposes and closing this issue.

**Comment by Keith94** [comment]
Thanks!!
